[program:queue-worker]
command=/usr/local/bin/php -d variables_order=EGPCS /var/www/html/artisan queue:work --sleep=3 --tries=1 --timeout=9000 --max-time=3600
user=sail
numprocs=4
process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
