const ADJECTIVES = [
    'Secret',
    'Haunted',
    'Jittery',
    'Overcaffeinated',
    'Mythic',
    'Bouncy',
    'Soggy',
    'Cursed',
    'Polite',
    'Chaotic',
    'Suspicious',
    'Tiny',
    'Massive',
    'Sleepy',
    'Turbo',
    'Disco',
    'Forbidden',
    'Glittery',
    'Crunchy',
    'Eldritch',
    'Wobbly',
    'Royal',
    'Undercover',
    'Laser',
    'Pixelated',
    'Vintage',
    'Quantum',
    'Unreasonably',
    'Extremely',
    'Barely',
    'Accidentally',
    'Legendary',
    'Unfinished',
    'Premium',
    'Budget',
    'Cosmic',
    'Indoor',
    'Outdoor',
    'Underground',
    'Floating',
    'Diagonal',
    'Backwards',
    'Official',
    'Unofficial',
    'Suspiciously',
    'Probably',
    'Definitely',
    'Maybe',
    'Ultra',
    'Mega',
    'Nano',
    'Giga',
    'Micro',
    'Macro',
    'Hyper',
    'Hypo',
    'Turbocharged',
    'Hand-stitched',
    'Machine-washed',
    'Dry-clean',
    'Non-euclidean',
    'Euclidean',
    'Top-secret',
    'Open-source',
    'Closed-beta',
    'Early-access',
    'Late-access',
    'Season-pass',
    'Limited-edition',
    'Unlimited',
    'Finite',
    'Infinite',
    'Recursive',
    'Self-referential',
    'Meta',
    'Postmodern',
    'Pre-apocalyptic',
    'Post-snack',
    'Mid-tier',
    'High-stakes',
    'Low-poly',
    'High-poly',
    'Procedural',
    'Hand-placed',
    'AI-assisted',
    'Human-approved',
    'Cat-approved',
    'Dog-tolerant',
    'Bird-free',
    'Moth-friendly',
    'Spider-neutral',
    'Wizard-owned',
    'Knight-operated',
    'Rogue-certified',
    'Bard-sanctioned',
    'Cleric-blessed',
    'Druidic',
    'Paladin-polished',
    'Warlock-wired',
    'Sorcerer-spun',
    'Ranger-rated',
    'Monk-minimalist',
    'Barbarian-branded',
    'Fighter-funded',
    'Artificer-assembled',
];

const NOUNS = [
    'Bog',
    'Plateau',
    'Snackatorium',
    'Hexagon',
    'Puddle',
    'Volcano',
    'Meadow',
    'Dungeon',
    'Parking Lot',
    'Lunchroom',
    'Basement',
    'Attic',
    'Elevator Shaft',
    'Cornfield',
    'Aquarium',
    'Junkyard',
    'Ball Pit',
    'Maze',
    'Labyrinth',
    'Pantry',
    'Greenhouse',
    'Iceberg',
    'Sandwich',
    'Waffle',
    'Pancake Dimension',
    'Sock Drawer',
    'Toolbox',
    'Junk Drawer',
    'Closet',
    'Garage',
    'Treehouse',
    'Igloo',
    'Ziggurat',
    'Pyramid Scheme',
    'Crater',
    'Ravine',
    'Fjord',
    'Archipelago',
    'Atoll',
    'Sandbar',
    'Reef',
    'Trench',
    'Plate Boundary',
    'Fault Line',
    'Hot Spring',
    'Cold Spring',
    'Lily Pad',
    'Mushroom Ring',
    'Stonehenge Knockoff',
    'Ruins',
    'Castle',
    'Fort',
    'Outpost',
    'Trading Post',
    'Tavern',
    'Inn',
    'Shrine',
    'Obelisk',
    'Monolith',
    'Totem',
    'Totem Pole',
    'Windmill',
    'Waterwheel',
    'Aqueduct',
    'Bridge',
    'Tunnel',
    'Cave',
    'Cavern',
    'Grotto',
    'Sinkhole',
    'Quicksand Pit',
    'Tar Pit',
    'Salt Flat',
    'Badlands',
    'Tundra',
    'Steppe',
    'Savanna',
    'Rainforest',
    'Cloud Forest',
    'Bamboo Grove',
    'Cherry Orchard',
    'Vineyard',
    'Pumpkin Patch',
    'Corn Maze',
    'Hay Bale',
    'Scarecrow District',
    'Wind Farm',
    'Solar Farm',
    'Data Center',
    'Server Room',
    'Loading Zone',
    'Spawn Point',
    'Checkpoint',
    'Boss Arena',
    'Loot Room',
    'Secret Room',
    'Easter Egg',
    'Side Quest',
    'Main Quest',
    'Tutorial Zone',
    'Endgame',
    'New Game+',
    'Hard Mode',
    'Easy Street',
    'Difficulty Spike',
    'Rubberband AI',
    'Lag Spike',
    'Rubber Room',
    'Green Room',
    'Waiting Room',
    'Lobby',
    'Queue',
    'Loading Bar',
    'Progress Bar',
    'Health Bar',
    'Mana Pool',
    'Stamina Ring',
    'Cooldown',
    'Buff Zone',
    'Debuff Swamp',
    'Status Effect',
    'Save Point',
    'Respawn',
    'Checkpoint Charlie',
    'Waypoint',
    'Fast Travel Node',
    'Portal',
    'Stargate',
    'Wormhole',
    'Black Hole',
    'White Hole',
    'Nebula',
    'Asteroid Belt',
    'Moon Base',
    'Space Station',
    'Dyson Sphere',
    'Ringworld',
    'Flat Earth',
    'Globe',
    'Atlas',
    'Map Fold',
    'Legend',
    'Scale Bar',
    'North Arrow',
    'Compass Rose',
    'Grid Square',
    'Hex Cell',
    'Vertex',
    'Edge Case',
    'Corner Case',
    'Happy Path',
    'Sad Path',
    'Critical Path',
    'Garden Path',
    'Primrose Path',
    'Yellow Brick Road',
    'Red Carpet',
    'Blue Screen',
    'Green Screen',
    'Chroma Key',
    'Alpha Channel',
    'Beta Channel',
    'Gamma Ray',
    'Delta Force',
    'Epsilon',
    'Zeta',
    'Omega Zone',
];

function pick<T>(items: readonly T[]): T {
    return items[Math.floor(Math.random() * items.length)]!;
}

/**
 * Silly default names for new or generated maps (replaces “Untitled” / “Generated map”).
 */
export function randomWackyMapName(): string {
    return `${pick(ADJECTIVES)} ${pick(NOUNS)}`;
}
